---
- name: Ensure Ansible downloads directory exists.
  file:
    path: "{{ downloads }}"
    state: directory

- name: Symlink /usr/local/etc/ansible to /etc/ansible.
  file:
    dest: /etc/ansible
    src: /usr/local/etc/ansible
    state: link
  sudo: yes
